function myfunction(){
    document.getElementById("Image1").src = "via1.jpg"
    document.getElementById("Image2").src = "via2.jpg"
    document.getElementById("Image3").src = "via3.jpg"
    document.getElementById("Image4").src = "via4.jpg"
    document.getElementById("Image5").src = "via5.jpg"
    document.getElementById("Image6").src = "via6.jpg"
    document.getElementById("Image7").src = "via7.jpg"
    document.getElementById("Image8").src = "via8.jpg"
    document.getElementById("Image9").src = "via9.jpg"
    document.getElementById("Image10").src = "via10.jpeg"
    document.getElementById("Image11").src = "via11.jpeg"
    document.getElementById("Image12").src = "via12.jpeg"
    document.getElementById("Image13").src = "via13.jpeg"
    document.getElementById("Align1").innerHTML = "The Most Beautiful Girl In The World"
    document.getElementById("Align2").innerHTML = "It's You <3<3<3"
    document.getElementById("Align3").innerHTML = ""
    document.getElementById("Align4").innerHTML = ""
    document.getElementById("Align5").innerHTML = ""
    document.getElementById("Align6").innerHTML = ""
    document.getElementById("Align7").innerHTML = ""
}